In [ ]:
print("hello")

hello


## diffrent operation on **array** and **list**

In [ ]:
import numpy as np
l1=[20,30,12]
l2=[50,20,30]
print(l1+l2)#concatination



[20, 30, 12, 50, 20, 30]


In [ ]:
a=np.array([20,30,40,50,60])
b=np.array([30])
print(a+b)# addition
print(a*b)# multiplication
print(a-b)# subtrraction

[50 60 70 80 90]
[ 600  900 1200 1500 1800]
[-10   0  10  20  30]


In [ ]:
c=np.array([20,30,"12"])
print(c)#array cant hold uo multiple data type so if one string then convert all of them as string

['20' '30' '12']


**slicing**

In [ ]:
print(a[0:2])

[20 30]


In [ ]:
d=np.array([[10,20,30,40,50],[1,2,3,4,5]])
print(d)


[[10 20 30 40 50]
 [ 1  2  3  4  5]]


In [ ]:
print(d[0:2,0:2])#slicing must be done in the same order as of the array declared

[[10 20]
 [ 1  2]]


# diffrent attributes of **array**

In [ ]:
print(np.shape(d))#rows,col
print(np.size(d))#total no. of elements
print(np.ndim(d))#dimenssion
print(a.dtype)#data type used by array
print(len(d))# in simple number of rows
print(d.shape)#rows,col
print(type(d))#say about whose array is this
print(d.astype(float))#type cast in float

(2, 5)
10
2
int64
2
(2, 5)
<class 'numpy.ndarray'>
[[10. 20. 30. 40. 50.]
 [ 1.  2.  3.  4.  5.]]


mathemetical **functions**

In [ ]:
m=np.array([[20,30,40,50],[2,3,4,5]])
n=np.array([[2,3,4,5],[20,30,40,50]])
print(np.add(m,n))

[[22 33 44 55]
 [22 33 44 55]]


In [ ]:
print(np.subtract(m,n))

[[ 18  27  36  45]
 [-18 -27 -36 -45]]


In [ ]:
print(np.multiply(m,n))

[[ 40  90 160 250]
 [ 40  90 160 250]]


In [ ]:
print(np.divide(m,n))

[[10.  10.  10.  10. ]
 [ 0.1  0.1  0.1  0.1]]


In [ ]:
k=np.array([3])

In [ ]:
print(np.power(m,k))

[[  8000  27000  64000 125000]
 [     8     27     64    125]]


In [ ]:
print(np.sqrt(m))

[[4.47213595 5.47722558 6.32455532 7.07106781]
 [1.41421356 1.73205081 2.         2.23606798]]


combining  and splittiing **array**

In [ ]:
arr1= np.array([1,2,3])
arr2=np.array([3,2,1])
print(np.concatenate([arr1,arr2],axis=0))#for multi_dimenssion array it can be more than 0

[1 2 3 3 2 1]


In [ ]:
print(np.hstack([arr1,arr2]))#simmilarly for vertical kindly try them with atleast 2_d array

[1 2 3 3 2 1]


In [ ]:
print(np.array_split(a,3))

[array([20, 30]), array([40, 50]), array([60])]


# adding and removing elements from array

In [ ]:
print(a)


[20 30 40 50 60]


In [ ]:
print(np.append(70,a))#70 has been appended at the starting

[70 20 30 40 50 60]


In [ ]:
arr3=np.array([[4,5,6],[7,8,9]])
print(np.append(arr3,[11,12]))#now appended at the end bcz element is mentioned at the  end

[ 4  5  6  7  8  9 11 12]


In [ ]:
print(a)


[20 30 40 50 60]


In [ ]:
print(np.insert(a,1,100))#at the  1 index 100 has been inserted (array,index,value)

[ 20 100  30  40  50  60]


In [ ]:
print(np.insert(a,1,[200,300]))

[ 20 200 300  30  40  50  60]


In [ ]:
print(arr3)

[[4 5 6]
 [7 8 9]]


In [ ]:
print(np.insert(arr3,1,[400,500], axis=1))# remember axis more then one is for multidimenssion array

[[  4 400   5   6]
 [  7 500   8   9]]


In [ ]:
print(np.insert(arr3,[1,3],[0],axis=1))

[[4 0 5 6 0]
 [7 0 8 9 0]]


In [ ]:
print(a)

[20 30 40 50 60]


In [ ]:
print(np.delete(a,1))

[20 40 50 60]


In [ ]:
print(arr3)

[[4 5 6]
 [7 8 9]]


In [ ]:
print(np.delete(arr3,1))

[4 6 7 8 9]


In [ ]:
print(np.delete(arr3,1,axis=0))

[[4 5 6]]


In [ ]:
print(np.delete(arr3,1,axis=1))

[[4 6]
 [7 9]]


# numpy== sort,filter,search

In [ ]:
arr4=np.array([4,8,7,9,6])
print(arr4)

[4 8 7 9 6]


In [ ]:
arr5=np.array([[7,8,9,3],[4,7,5,1]])

In [ ]:
print(np.sort(arr5))

[[3 7 8 9]
 [1 4 5 7]]


In [ ]:
print(np.sort(arr4))

[4 6 7 8 9]


In [ ]:
print(np.where(arr4==8))

(array([1]),)


In [ ]:
print(np.where(arr4%2==0))

(array([0, 1, 4]),)


In [ ]:
arr6=np.array([1,2,3,4,5,6])
fa=[True,True,True,False,False,False]#this will returen the elemntes or which the true iis assing
new=arr6[fa]
print(new)

[1 2 3]


In [ ]:
ss=np.searchsorted(arr6,5)#use for searching an element in sorted array
print(ss)

4


In [ ]:
#print(np.fa[True,False,True,False,True,False]) === wrong way to done

# aggregating functions in numpy

In [7]:
import numpy as np

In [9]:
arr7=np.array([4,5,7,8])
print(arr7)

[4 5 7 8]


In [10]:
print(np.sum(arr7))#addition of values in array

24


In [14]:
print(np.min(arr7))#minimum
print(np.max(arr7))#maximum
print(np.size(arr7))#total number of elements in array
print(np.mean(arr7))#mean of the array

4
8
4
6.0


In [17]:
print(np.cumsum(arr7))#print comulative sum of the array
print(np.cumprod(arr7))#return the commulative  product of the array

[ 4  9 16 24]
[   4   20  140 1120]


# lets take an problem having price array and the quantity array find the **total** **amount**

In [35]:
price=np.array([10,20,30,40])
qunt=np.array([1,2,3,4])
print(price)
print()
arr8=np.cumprod([price,qunt],axis=0)

[10 20 30 40]



In [36]:
print(arr8)

[[ 10  20  30  40]
 [ 10  40  90 160]]


In [37]:
arr9=arr8[1]

In [38]:
print(np.sum(arr9))#hence the sum has been  obtained

300


# statistical functions in numpy array

In [39]:
import numpy as np

In [47]:
baked_food=np.array([100,200,300,300,400,500])#amount of carbohydrate in baked food
print(np.mean(baked_food))#gives mean of the carbohydrate values

300.0


In [48]:
print(np.median(baked_food))#median is the center/avg of center values after the data has benn sorted

300.0


In [45]:
#print(np.mode(baked_food))=== remember for finding the mode you have to import the "statistic laibrery" from paython

In [53]:
import statistics as stati
print(stati.mode(baked_food))#note if all occures only once the first value is returnd

300


In [54]:
print(np.std(baked_food))#stnder_deviation tells about how much diffrenece of all the values compare to the mean value
print()#try to  make std as smaller as possible

129.09944487358058


In [57]:
print(np.var(baked_food))#it just the square of the std having simmilar significance

16666.666666666668


In [56]:
print(129*129)

16641


# lets take an axample to understand the correlation

In [58]:
smokking=np.array([10,20,30,40,50])
death=np.array([40,50,60,70,90])
print(np.corrcoef([smokking,death]))#correlation help me to find the relation in between the arrays -1<=corre<=1 (0=no relation,-1 inverslly realation,1 directly realted)

[[1.         0.98639392]
 [0.98639392 1.        ]]
